apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deployment.triggered
      requests:
        - >-
          curl --request POST http://dynatrace:1197edc464a6c0b7aa5e6d0f72039229db@jenkins.54.242.152.223.nip.io/job/demo-quality-gates-jenkins/job/1.%20Build/build
      subscriptionID: 58c0792b-76a3-4212-8cd0-4e46a117e562
      sendFinished: true
      sendStarted: true
