apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.deployment.triggered
      requests:
        - >-
          curl --request POST http://ramvasu:11e0948df08b52acf9ddd90fae26e52660@localhost:8080/job/first%20pipeline/build
      subscriptionID: 09fe22e4-7997-4324-beea-eb83e1d5c424
      sendFinished: true
      sendStarted: true
