apiVersion: webhookconfig.keptn.sh/v1alpha1
kind: WebhookConfig
metadata:
  name: webhook-configuration
spec:
  webhooks:
    - type: sh.keptn.event.evaluation.triggered
      requests:
        - >-
          curl --request POST http://dynatrace:{{.env.secret_jenkins_JKTOKEN}}@jenkins.54.242.152.223.nip.io/job/demo-quality-gates-jenkins/job/1.%20Build/buildWithParameters?build=2
      envFrom:
        - name: secret_jenkins_JKTOKEN
          secretRef:
            name: jenkins
            key: JK_TOKEN
      subscriptionID: f5e09629-7c9a-4c69-9578-3c683fb31123
      sendFinished: false
      sendStarted: false
